<?xml version="1.0" encoding="utf-8"?><Database Name="QLLinhKienDienTu" Class="dbQLLinhKienDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=DESKTOP-K7BRREB;Initial Catalog=QLLinhKienDienTu;Persist Security Info=True;User ID=sa" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="QLLinhKienDienTuConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.ChiTietDonHang" Member="ChiTietDonHangs">
    <Type Name="ChiTietDonHang">
      <Column Name="MaDonHang" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MaSP" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="SoLuong" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DonGia" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="DonHang_ChiTietDonHang" Member="DonHang" ThisKey="MaDonHang" OtherKey="MaDonHang" Type="DonHang" IsForeignKey="true" />
      <Association Name="SanPham_ChiTietDonHang" Member="SanPham" ThisKey="MaSP" OtherKey="MaSP" Type="SanPham" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.DonHang" Member="DonHangs">
    <Type Name="DonHang">
      <Column Name="MaDonHang" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="NgayGiao" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="NgayDat" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="TinhTrangGiaoHang" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="UserName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="DonHang_ChiTietDonHang" Member="ChiTietDonHangs" ThisKey="MaDonHang" OtherKey="MaDonHang" Type="ChiTietDonHang" />
      <Association Name="KhachHang_DonHang" Member="KhachHang" ThisKey="UserName" OtherKey="UserName" Type="KhachHang" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.KhachHang" Member="KhachHangs">
    <Type Name="KhachHang">
      <Column Name="UserName" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="HoTen" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="DienThoai" Type="System.String" DbType="VarChar(12)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="DiaChi" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="MatKhau" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="KhachHang_DonHang" Member="DonHangs" ThisKey="UserName" OtherKey="UserName" Type="DonHang" />
    </Type>
  </Table>
  <Table Name="dbo.Loai" Member="Loais">
    <Type Name="Loai">
      <Column Name="MaLoai" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TenLoai" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="NoTe" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="Loai_SanPham" Member="SanPhams" ThisKey="MaLoai" OtherKey="MaLoai" Type="SanPham" />
    </Type>
  </Table>
  <Table Name="dbo.SanPham" Member="SanPhams">
    <Type Name="SanPham">
      <Column Name="MaSP" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TenSP" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="GiaBan" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MoTa" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="Anh" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="SLTon" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MaLoai" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="SanPham_ChiTietDonHang" Member="ChiTietDonHangs" ThisKey="MaSP" OtherKey="MaSP" Type="ChiTietDonHang" />
      <Association Name="Loai_SanPham" Member="Loai" ThisKey="MaLoai" OtherKey="MaLoai" Type="Loai" IsForeignKey="true" />
    </Type>
  </Table>
</Database>